# .github/workflows/CI-01_test-build-devcontainer-image.yml

# Workflow Name: Test Build Dev Container Image
# Description: This workflow is responsible for test building Dev Container images for pull requests.

name: "Test Build Dev Container Image"

# Concurrency ensures that only one workflow run is in progress for a given branch/tag.
# This prevents race conditions during build and push operations.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Triggers for the workflow
on:
  workflow_dispatch: # Allows manual triggering of the workflow.
  pull_request:
    branches:
      - main # Trigger for pull requests to the main branch.

# Environment variables used across all jobs.
env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/devcontainers/m365-dev

jobs:
  build:
    name: "Build Test Image"
    permissions:
      contents: read # Required for checking out the code.

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: ${{ env.IMAGE_NAME }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern=weekly
            type=semver,pattern={{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=ref,event=branch
            type=ref,event=pr
          sep-tags: ","
          flavor: |
            latest=false
            prefix=
            suffix=-amd64

      - name: Update Tags to Fit into devcontainers/cli format
        id: dcmeta
        run: |
          prefix="${{ env.IMAGE_NAME }}"
          input_list="$DOCKER_METADATA_OUTPUT_TAGS"
          delimiter=","

          result_list=$(echo "$input_list" | sed "s|${prefix}:||g")

          echo "primary_tag_amd64=${result_list%%,*}" >> "$GITHUB_OUTPUT"
          echo "tags=$result_list" >> "$GITHUB_OUTPUT"

      - name: "[amd64] Pre-build Dev Container Image"
        uses: devcontainers/ci@v0.3
        env:
          # see: https://github.com/devcontainers/ci/issues/191#issuecomment-1603857155
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          subFolder: .devcontainer/src
          configFile: .devcontainer/src/devcontainer.json
          platform: linux/amd64
          cacheFrom: ${{ env.IMAGE_NAME }}
          imageName: ${{ env.IMAGE_NAME }}
          imageTag: ${{ steps.dcmeta.outputs.tags }}
          push: never
          skipContainerUserIdUpdate: true
